name: Basira
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2


  permission_handler: ^11.4.0
  flutter_tts: ^4.2.2
  camera: ^0.10.4
  path: ^1.8.3
  image: ^3.3.0
  path_provider: ^2.0.11
  flutter_vision: ^1.1.4
  
  google_mlkit_text_recognition: ^0.15.0
  
  google_mlkit_object_detection: ^0.15.0
  vibration: ^3.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.0
  http: ^1.3.0
  sensors_plus: ^3.0.3
  just_audio: ^0.9.34
  speech_to_text: ^7.0.0
  flutter_speech: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/bass.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/
  - assets/models/bestlast_float16.tflite
  - assets/models/best_float16.tflite
  - assets/models/newlabels.txt
  - assets/models/moneylabels.txt
  - assets/icons/money.png
  - assets/icons/obj.png
  - assets/icons/text.png
  - assets/icons/objdet.jpg
  - assets/icons/bass.png
  - assets/icons/moneyd.jpg
  - assets/icons/textd.jpg
  - assets/icons/welcomep.jpg
  - assets/credentials/visionkey.json
  - assets/icons/logo.png
